services:
  - type: web
    name: ticketing-agent
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn ticketing_agent:app --host 0.0.0.0 --port 10000
    envVars:
      - key: WHOP_API_KEY
        sync: false
      - key: WHOP_APP_ID
        sync: false
      - key: WHOP_AGENT_USER_ID
        sync: false
    disk:
      name: faiss-index
      mountPath: /app/faiss_index
      sizeGB: 1
      # Add another disk for chat_histories
      # Uncomment if you want chat history persistence
      - name: chat-histories
        mountPath: /app/chat_histories
        sizeGB: 1
      #  mountPath: /app/chat_histories
      #  sizeGB: 1
